language: node_js

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi

node_js:
  - '7'

script:
  - npm rebuild node-sass
  - yarn run check-ci

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
